<a href="https://colab.research.google.com/github/JellyBeans2022/Hands-On-Practices-Python-R-/blob/main/MNIST_with_Tens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Working with MNIST data - Tensorflow**

In [ ]:
print(tf.__version__)
# Importing the data set
mnist = tf.keras.datasets.mnist

In [ ]:
# Download train and test set seperately
(X_train,Y_train), (x_test,y_test) = mnist.load_data()

In [ ]:
X_train, x_test = (X_train/255.0), (x_test/255.0)

In [ ]:
# Building the model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [ ]:
# Generating the predictions
predictions = model(X_train[:1]).numpy()
predictions

array([[-0.20693363,  0.03566077, -0.22227491, -0.8665309 , -0.08155899,
        -0.03898935,  0.9069829 ,  0.4241465 , -0.34250113, -0.97259986]],
      dtype=float32)

In [ ]:
# Converting above probabilities
tf.nn.softmax(predictions).numpy()

array([[0.08092593, 0.10314426, 0.07969389, 0.04184352, 0.09173544,
        0.0957249 , 0.24652188, 0.15211159, 0.07066615, 0.0376325 ]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn
# This loss equal to the negative log probability of the true class.
# It is zero, if the model is sure of the correct class

In [ ]:
loss_fn(Y_train[:1],predictions).numpy()

2.3462768

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
# Use to adjusts the model parameters to minimize the loss
model.fit(X_train, Y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2922 - accuracy: 0.9154
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1407 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1051 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0844 - accuracy: 0.9746
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0740 - accuracy: 0.9771


In [ ]:
# Check the model performance
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0729 - accuracy: 0.9777 - 424ms/epoch - 1ms/step


[0.07287350296974182, 0.9776999950408936]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
# Predicting the test test
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.9758178e-07, 2.1446134e-07, 1.5439635e-05, 3.2626334e-04,
        8.5458758e-12, 5.2434882e-07, 1.0479767e-13, 9.9965727e-01,
        5.4164158e-08, 9.7504135e-08],
       [2.3750831e-08, 5.8020596e-05, 9.9987841e-01, 6.2796687e-05,
        7.0723909e-18, 3.6755446e-07, 3.7762495e-09, 5.5051195e-13,
        3.0620254e-07, 4.0084663e-12],
       [2.0964956e-07, 9.9799371e-01, 6.2948820e-04, 1.2115630e-05,
        2.8079778e-05, 2.0439900e-06, 2.9371711e-06, 1.2412103e-03,
        8.7497654e-05, 2.7342064e-06],
       [9.9990594e-01, 9.3489316e-10, 8.4874751e-05, 4.9819022e-07,
        1.8920774e-08, 4.5793209e-07, 4.1071539e-06, 4.5749778e-07,
        4.3251884e-08, 3.5447033e-06],
       [3.1545296e-06, 4.4634774e-08, 2.8965872e-04, 1.3280933e-06,
        9.9725395e-01, 8.8592888e-06, 1.4171179e-05, 4.4376869e-05,
        2.8227228e-06, 2.3816386e-03]], dtype=float32)>